services:
  mysql:
    image: mysql:8.0.32
    container_name: db-mysql
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./src/infrastructure/database/typeorm/migrations/database.sql:/docker-entrypoint-initdb.d/database.sql
